#!/bin/sh
set -e

lb config noauto \
    --distribution trixie \
    --architectures amd64 \
    --bootloader grub-efi-amd64 \
    --binary-images iso-hybrid \
    --archive-areas "main contrib non-free non-free-firmware" \
    --debian-installer none \
    --bootappend-live "boot=live components quiet splash" \
    "${@}"
